# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default
      vmImage: ubuntu-latest
    steps:
 
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Registry Service'
        repository: 'juuniper/mywebapp'
        command: 'buildAndPush'
        Dockerfile: '**/dockerfile'
        tags: |
          $(tag)

- stage: Provision
  displayName: 'Creating terraform on Azure'
  dependsOn: Build
  jobs:
  - job: Provision
    displayName: 'Provision container instance'
    pool:
      name: Default
      vmImage: ubuntu-latest
    variables:
    - group: TF_sample_library
    steps:
      - script: |
          set -e
          terraform init -input=false
          terraform apply -input=false -auto-approve -var="image_build=$(tag)"
        name: 'RunTerraform'
        displayName: 'Run Terraform'
        env:
          ARM_CLIENT_ID: $(ARM_CLIENT_ID)
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
          ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
          ARM_TENANT_ID: $(ARM_TENANT_ID)
          TF_VAR_image_build: $(tag)